Repository opendatadiscovery/odd-collector, pull requests merged in 2022-08, with the labels that each got.

#49 Port ODBC adapter to collector #19. Add class diagram.
  Dockerfile
  README.md
  adapter_domain_classes.png
  config_examples/odbc.yaml
  docker/testodbc.yaml
  domain_classes.plantuml
  odd_collector/adapters/odbc/README.md
  odd_collector/adapters/odbc/__init__.py
  odd_collector/adapters/odbc/adapter.py
  odd_collector/adapters/odbc/connection.py
  odd_collector/adapters/odbc/exception.py
  odd_collector/adapters/odbc/mappers/__init__.py
  odd_collector/adapters/odbc/mappers/columns.py
  odd_collector/adapters/odbc/mappers/helpers.py
  odd_collector/adapters/odbc/mappers/tables.py
  odd_collector/adapters/odbc/mappers/types.py
  odd_collector/adapters/odbc/odbc_repository.py
  odd_collector/adapters/odbc/odbc_repository_base.py
  odd_collector/domain/plugin.py
Labels: chore

#75 Feature/lineage datasources
  collector_config.yaml
  odd_collector/adapters/tableau/adapter.py
  odd_collector/adapters/tableau/client.py
  odd_collector/adapters/tableau/domain/__init__.py
  odd_collector/adapters/tableau/domain/column.py
  odd_collector/adapters/tableau/domain/sheet.py
  odd_collector/adapters/tableau/domain/table.py
  odd_collector/adapters/tableau/mappers/columns.py
  odd_collector/adapters/tableau/mappers/metadata.py
  odd_collector/adapters/tableau/mappers/sheets.py
  odd_collector/adapters/tableau/mappers/tables.py
  odd_collector/adapters/tableau/query.py
  odd_collector/adapters/tableau/tests/__init__.py
  odd_collector/adapters/tableau/tests/test_map_column.py
  odd_collector/adapters/tableau/tests/test_map_sheet.py
  odd_collector/adapters/tableau/tests/test_map_table.py
  odd_collector/adapters/tableau/tests/test_parse_column.py
  odd_collector/adapters/tableau/tests/test_parse_sheets.py
  odd_collector/adapters/tableau/tests/test_parse_tables.py
  odd_collector/adapters/tableau/tests/test_table_model.py
  odd_collector/adapters/tableau/tests/test_tableau_adapter.py
  poetry.lock
  pyproject.toml
Labels: enhancement

#80 Added vertica repository
  README.md
  config_examples/vertica.yaml
  odd_collector/adapters/vertica/__init__.py
  odd_collector/adapters/vertica/adapter.py
  odd_collector/adapters/vertica/domain/__init__.py
  odd_collector/adapters/vertica/domain/column.py
  odd_collector/adapters/vertica/domain/table.py
  odd_collector/adapters/vertica/logger.py
  odd_collector/adapters/vertica/mapper/__init__.py
  odd_collector/adapters/vertica/mapper/columns.py
  odd_collector/adapters/vertica/mapper/metadata.py
  odd_collector/adapters/vertica/mapper/tables.py
  odd_collector/adapters/vertica/mapper/types.py
  odd_collector/adapters/vertica/mapper/views.py
  odd_collector/adapters/vertica/tests/__init__.py
  odd_collector/adapters/vertica/tests/test_map_table_column.py
  odd_collector/adapters/vertica/tests/test_model_column.py
  odd_collector/adapters/vertica/tests/test_model_table.py
  odd_collector/adapters/vertica/tests/test_vertica_adapter.py
  odd_collector/adapters/vertica/vertica_connector.py
  odd_collector/adapters/vertica/vertica_repository.py
  odd_collector/adapters/vertica/vertica_repository_base.py
  odd_collector/domain/plugin.py
  pyproject.toml
Labels: kind: feature, chore
