Repository opendatadiscovery/odd-collector, pull requests merged in 2022-05, with the labels that each got.

#7 elasticsearch adapter integrated
  README.md
  odd_collector/adapters/elasticsearch/__init__.py
  odd_collector/adapters/elasticsearch/adapter.py
  odd_collector/adapters/elasticsearch/mappers/__init__.py
  odd_collector/adapters/elasticsearch/mappers/fields.py
  odd_collector/adapters/elasticsearch/mappers/indexes.py
  odd_collector/adapters/elasticsearch/mappers/metadata.py
  odd_collector/domain/plugin.py
  poetry.lock
  pyproject.toml
Labels: enhancement, chore

#8 Remove obsolete provider_oddrn out of collector_config example
  collector_config.yaml
Labels: enhancement

#10 feast adapter implemented
  README.md
  odd_collector/adapters/feast/__init__.py
  odd_collector/adapters/feast/adapter.py
  odd_collector/adapters/feast/mappers/__init__.py
  odd_collector/adapters/feast/mappers/dataset_fields.py
  odd_collector/adapters/feast/mappers/datasets.py
  odd_collector/adapters/feast/mappers/metadata.py
  odd_collector/adapters/feast/mappers/types.py
  odd_collector/domain/plugin.py
  poetry.lock
  pyproject.toml
Labels: enhancement, chore

#13 Feat/tarantool
  README.md
  collector_config.yaml
  odd_collector/adapters/tarantool/__init__.py
  odd_collector/adapters/tarantool/adapter.py
  odd_collector/adapters/tarantool/mappers/__init__.py
  odd_collector/adapters/tarantool/mappers/columns.py
  odd_collector/adapters/tarantool/mappers/metadata.py
  odd_collector/adapters/tarantool/mappers/spaces.py
  odd_collector/adapters/tarantool/mappers/types.py
  odd_collector/domain/plugin.py
  poetry.lock
  pyproject.toml
Labels: kind: feature, chore

#14 feat: tableau adapter implemented
  README.md
  collector_config.yaml
  odd_collector/adapters/tableau/__init__.py
  odd_collector/adapters/tableau/adapter.py
  odd_collector/adapters/tableau/client.py
  odd_collector/adapters/tableau/mappers/__init__.py
  odd_collector/adapters/tableau/mappers/columns.py
  odd_collector/adapters/tableau/mappers/metadata.py
  odd_collector/adapters/tableau/mappers/sheets.py
  odd_collector/adapters/tableau/mappers/tables.py
  odd_collector/adapters/tableau/mappers/types.py
  odd_collector/adapters/tableau/query.py
  odd_collector/domain/plugin.py
  poetry.lock
  pyproject.toml
Labels: chore

#15 neo4j adapter implemented
  odd_collector/adapters/neo4j/__init__.py
  odd_collector/adapters/neo4j/adapter.py
  odd_collector/adapters/neo4j/mappers/__init__.py
  odd_collector/adapters/neo4j/mappers/fields.py
  odd_collector/adapters/neo4j/mappers/metadata.py
  odd_collector/adapters/neo4j/mappers/nodes.py
  odd_collector/adapters/neo4j/mappers/types.py
  odd_collector/domain/plugin.py
  poetry.lock
  pyproject.toml
Labels: kind: enhancement, enhancement

#16 docs: add neoj4 example
  README.md
Labels: chore
