Repository opendatadiscovery/odd-collector, pull requests merged in 2022-06, with the labels that each got.

#18 Feature/dbt
  odd_collector/adapters/dbt/__init__.py
  odd_collector/adapters/dbt/adapter.py
  odd_collector/adapters/dbt/mappers/__init__.py
  odd_collector/adapters/dbt/mappers/columns.py
  odd_collector/adapters/dbt/mappers/metadata.py
  odd_collector/adapters/dbt/mappers/tables.py
  odd_collector/adapters/dbt/mappers/types.py
  odd_collector/domain/plugin.py
  poetry.lock
Labels: enhancement

#21 Type enhancement
  odd_collector/adapters/clickhouse/mappers/columns.py
Labels: bug

#26 Kafka
  Dockerfile
  collector_config.yaml
  odd_collector/adapters/kafka/__init__.py
  odd_collector/adapters/kafka/adapter.py
  odd_collector/adapters/kafka/kafka_generator.py
  odd_collector/adapters/kafka/mappers/__init__.py
  odd_collector/adapters/kafka/mappers/avro_schema.py
  odd_collector/adapters/kafka/mappers/json_schema.py
  odd_collector/adapters/kafka/mappers/parser/__init__.py
  odd_collector/adapters/kafka/mappers/parser/abstract_parser.py
  odd_collector/adapters/kafka/mappers/parser/avro_parser.py
  odd_collector/adapters/kafka/mappers/parser/json_parser.py
  odd_collector/adapters/kafka/mappers/parser/nodes.py
  odd_collector/adapters/kafka/mappers/parser/types.py
  odd_collector/adapters/kafka/mappers/schemas.py
  odd_collector/adapters/kafka/readme.md
  odd_collector/domain/plugin.py
  poetry.lock
  pyproject.toml
  server.properties
  start.sh
  tests/__init__.py
  tests/test_kafka.py
Labels: chore

#31 Improve build processes
  .github/workflows/build.yaml
  .github/workflows/release-build.yaml
  .github/workflows/release-drafter.yaml
  Dockerfile
  docker/docker-compose.yml
  odd_collector/adapters/clickhouse/mappers/columns.py
  odd_collector/adapters/dbt/adapter.py
  odd_collector/adapters/dbt/mappers/__init__.py
  odd_collector/adapters/dbt/mappers/columns.py
  odd_collector/adapters/dbt/mappers/metadata.py
  odd_collector/adapters/dbt/mappers/tables.py
  odd_collector/adapters/dbt/mappers/types.py
  odd_collector/adapters/kafka/__init__.py
  odd_collector/adapters/kafka/adapter.py
  odd_collector/adapters/kafka/kafka_generator.py
  odd_collector/adapters/kafka/mappers/avro_schema.py
  odd_collector/adapters/kafka/mappers/json_schema.py
  odd_collector/adapters/kafka/mappers/parser/__init__.py
  odd_collector/adapters/kafka/mappers/parser/abstract_parser.py
  odd_collector/adapters/kafka/mappers/parser/avro_parser.py
  odd_collector/adapters/kafka/mappers/parser/json_parser.py
  odd_collector/adapters/kafka/mappers/parser/nodes.py
  odd_collector/adapters/kafka/mappers/schemas.py
  odd_collector/adapters/mssql/adapter.py
  odd_collector/adapters/mssql/mappers/__init__.py
  odd_collector/adapters/mssql/mappers/columns.py
  odd_collector/adapters/mssql/mappers/helpers.py
  odd_collector/adapters/mssql/mappers/tables.py
  odd_collector/adapters/mssql/mappers/types.py
  odd_collector/adapters/mssql/mappers/views.py
  odd_collector/adapters/neo4j/adapter.py
  odd_collector/adapters/neo4j/mappers/__init__.py
  odd_collector/adapters/neo4j/mappers/fields.py
  odd_collector/adapters/neo4j/mappers/metadata.py
  odd_collector/adapters/neo4j/mappers/nodes.py
  odd_collector/adapters/neo4j/mappers/types.py
  odd_collector/domain/plugin.py
  poetry.lock
Labels: kind: maintenance, scope: infrastructure
