Repository opendatadiscovery/odd-collector, pull requests merged in 2023-06, with the labels that each got.

#194 Sqlite support
  README.md
  config_examples/sqlite.yaml
  odd_collector/adapters/sqlite/__init__.py
  odd_collector/adapters/sqlite/adapter.py
  odd_collector/adapters/sqlite/domain/__init__.py
  odd_collector/adapters/sqlite/domain/column.py
  odd_collector/adapters/sqlite/domain/table.py
  odd_collector/adapters/sqlite/domain/view.py
  odd_collector/adapters/sqlite/mappers/__init__.py
  odd_collector/adapters/sqlite/mappers/column.py
  odd_collector/adapters/sqlite/mappers/column_type.py
  odd_collector/adapters/sqlite/mappers/database.py
  odd_collector/adapters/sqlite/mappers/table.py
  odd_collector/adapters/sqlite/mappers/view.py
  odd_collector/adapters/sqlite/repository/__init__.py
  odd_collector/adapters/sqlite/repository/base_repository.py
  odd_collector/adapters/sqlite/repository/sqlalchemy_repository.py
  odd_collector/domain/plugin.py
  poetry.lock
  pyproject.toml
Labels: chore

#195 Adapter for DuckDB
  config_examples/duckdb.yaml
  odd_collector/adapters/duckdb/__init__.py
  odd_collector/adapters/duckdb/adapter.py
  odd_collector/adapters/duckdb/client.py
  odd_collector/adapters/duckdb/grammar_parser/column_type.py
  odd_collector/adapters/duckdb/grammar_parser/exceptions.py
  odd_collector/adapters/duckdb/grammar_parser/field_types.lark
  odd_collector/adapters/duckdb/grammar_parser/parser.py
  odd_collector/adapters/duckdb/logger.py
  odd_collector/adapters/duckdb/mappers/__init__.py
  odd_collector/adapters/duckdb/mappers/catalog.py
  odd_collector/adapters/duckdb/mappers/column.py
  odd_collector/adapters/duckdb/mappers/models.py
  odd_collector/adapters/duckdb/mappers/schema.py
  odd_collector/adapters/duckdb/mappers/table.py
  odd_collector/adapters/duckdb/mappers/types.py
  odd_collector/domain/plugin.py
  pyproject.toml
Labels: enhancement

#199 198 clickhouse fix complex types in map data type
  odd_collector/adapters/clickhouse/domain/__init__.py
  odd_collector/adapters/clickhouse/domain/column.py
  odd_collector/adapters/clickhouse/grammar_parser/column_type.py
  odd_collector/adapters/clickhouse/grammar_parser/filed_types.lark
  odd_collector/adapters/clickhouse/grammar_parser/parser.py
  odd_collector/adapters/clickhouse/mappers/columns.py
  odd_collector/adapters/clickhouse/mappers/tables.py
  odd_collector/adapters/clickhouse/mappers/types.py
  tests/adapters/clickhouse/domain/test_grammar_parser.py
  tests/adapters/clickhouse/test_dataset_field_building.py
  tests/adapters/clickhouse/test_nested_transformer.py
  tests/adapters/clickhouse/test_type_trasformation.py
Labels: bug
