Repository opendatadiscovery/odd-collector, pull requests merged in 2023-01, with the labels that each got.

#133 build: bump sdk to 0.3.10
  Dockerfile
  poetry.lock
  pyproject.toml
Labels: bug

#141 [Issue/106] SingleStoreDB support
  README.md
  adapter_domain_classes.png
  config_examples/singlestore.yaml
  domain_classes.plantuml
  odd_collector/adapters/singlestore/__init__.py
  odd_collector/adapters/singlestore/adapter.py
  odd_collector/adapters/singlestore/logger.py
  odd_collector/adapters/singlestore/mappers/__init__.py
  odd_collector/adapters/singlestore/mappers/columns.py
  odd_collector/adapters/singlestore/mappers/metadata.py
  odd_collector/adapters/singlestore/mappers/models.py
  odd_collector/adapters/singlestore/mappers/tables.py
  odd_collector/adapters/singlestore/mappers/types.py
  odd_collector/adapters/singlestore/mappers/views.py
  odd_collector/adapters/singlestore/singlestore_repository.py
  odd_collector/adapters/singlestore/singlestore_repository_base.py
  odd_collector/domain/plugin.py
Labels: chore

#143 Feature/snowpipe
  odd_collector/adapters/snowflake/adapter.py
  odd_collector/adapters/snowflake/client.py
  odd_collector/adapters/snowflake/domain/__init__.py
  odd_collector/adapters/snowflake/domain/pipe.py
  odd_collector/adapters/snowflake/generator.py
  odd_collector/adapters/snowflake/map/__init__.py
  odd_collector/adapters/snowflake/map/column.py
  odd_collector/adapters/snowflake/map/database.py
  odd_collector/adapters/snowflake/map/pipe.py
  odd_collector/adapters/snowflake/map/schema.py
  odd_collector/adapters/snowflake/map/table.py
  odd_collector/adapters/snowflake/map/view.py
  poetry.lock
Labels: enhancement
